# 4a

In [1]:
import numpy as np

In [2]:
A = np.array([[5,1,8],[7,5,4]])
A

array([[5, 1, 8],
       [7, 5, 4]])

In [3]:
A.T

array([[5, 7],
       [1, 5],
       [8, 4]])

In [4]:
S = A@A.T
S

array([[90, 72],
       [72, 90]])

In [5]:
def tolatex_mat(M):
    for row in M:
        listr = row.tolist()
        converted_list = [str(element) for element in listr]
        joined_string = "&".join(converted_list)
        print(joined_string,"\\\\", sep="")
        
tolatex_mat(S)

90&72\\
72&90\\


In [6]:
np.linalg.det(S)

2916.000000000001

In [7]:
S.trace()

180

In [8]:
L_162=S-162*np.identity(2)
L_162

array([[-72.,  72.],
       [ 72., -72.]])

In [9]:
tolatex_mat(L_162)

-72.0&72.0\\
72.0&-72.0\\


In [10]:
L_18=S-18*np.identity(2)
L_18

array([[72., 72.],
       [72., 72.]])

In [11]:
tolatex_mat(L_18)

72.0&72.0\\
72.0&72.0\\


In [12]:
C=np.array([[1,0],[0,3]])
L=np.array([[1,1],[1,-1]])

In [13]:
Res = C@L@A

In [14]:
Res

array([[ 12,   6,  12],
       [ -6, -12,  12]])

In [15]:
tolatex_mat(Res)

12&6&12\\
-6&-12&12\\


In [16]:
Res = Res/18

In [17]:
Res[1]@Res[1]

1.0

In [18]:
Res

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.33333333, -0.66666667,  0.66666667]])

In [19]:
Res[0]@Res[1]

0.0

In [20]:
Solve_u2 = np.array([[2,1,2],[-1,-2,2]])
Solve_u2

array([[ 2,  1,  2],
       [-1, -2,  2]])

In [21]:
Solve_u2[0]=Solve_u2[0]+Solve_u2[1]
tolatex_mat(Solve_u2)

1&-1&4\\
-1&-2&2\\


In [22]:
Solve_u2[1]=Solve_u2[1]+Solve_u2[0]
tolatex_mat(Solve_u2)

1&-1&4\\
0&-3&6\\


In [23]:
Solve_u2[1]=Solve_u2[1]/-3
tolatex_mat(Solve_u2)

1&-1&4\\
0&1&-2\\


In [24]:
Solve_u2[0]=Solve_u2[0]+Solve_u2[1]
tolatex_mat(Solve_u2)

1&0&2\\
0&1&-2\\


In [25]:
u_3 = np.array([-2,2,1])
u_3@u_3

9

In [26]:
u_3 = u_3/3
u_3

array([-0.66666667,  0.66666667,  0.33333333])

In [27]:
D_t = np.vstack([np.array([[2,1,2],[-1,-2,2]])/3,u_3])
D_t

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.33333333, -0.66666667,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333]])

In [28]:
C = L/np.sqrt(2)

In [29]:
C

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [30]:
L = np.array([[9*np.sqrt(2),0,0],[0,3*np.sqrt(2),0]])
L

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        ,  4.24264069,  0.        ]])

In [31]:
C@L@D_t

array([[5., 1., 8.],
       [7., 5., 4.]])

In [32]:
C@np.delete(L, 2, 1)@np.delete(D_t, 2, 0)

array([[5., 1., 8.],
       [7., 5., 4.]])

# 4b

In [33]:
A = np.array([[1, 1 ,  2 ,  2],[2 ,  2 ,  1,   1]])
A.T

array([[1, 2],
       [1, 2],
       [2, 1],
       [2, 1]])

In [34]:
S=A@A.T

In [35]:
S

array([[10,  8],
       [ 8, 10]])

In [36]:
S.trace()

20

In [37]:
np.linalg.det(S)

36.0

In [38]:
inv_l = np.array([[1,0],[0,3]])
c_t = np.array([[1,1],[1,-1]])
c_t

array([[ 1,  1],
       [ 1, -1]])

In [39]:
d1_t= inv_l@c_t@A/6
d1_t

array([[ 0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5]])

In [40]:
d1_t[0]@d1_t[0]

1.0

In [41]:
d1_t[0]@d1_t[1]

0.0

In [42]:
d1_t[1]@d1_t[1]

1.0

In [43]:
d2_find = 2*d1_t
d2_find

array([[ 1.,  1.,  1.,  1.],
       [-1., -1.,  1.,  1.]])

In [44]:
d2_find[1]+=d2_find[0]
d2_find

array([[1., 1., 1., 1.],
       [0., 0., 2., 2.]])

In [45]:
d2_find[1]=d2_find[1]/2
d2_find

array([[1., 1., 1., 1.],
       [0., 0., 1., 1.]])

In [46]:
d2_find[0]-=d2_find[1]
d2_find

array([[1., 1., 0., 0.],
       [0., 0., 1., 1.]])

In [47]:
d2_find[0]@d2_find[0]

2.0

In [48]:
C

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [49]:
L = np.array([[3*np.sqrt(2),0,0,0],[0,np.sqrt(2),0,0]])
L

array([[4.24264069, 0.        , 0.        , 0.        ],
       [0.        , 1.41421356, 0.        , 0.        ]])

In [50]:
d1_t

array([[ 0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5]])

In [51]:
D_t = np.vstack([d1_t,np.array([[0,0,-1,1],[-1,1,0,0]])/np.sqrt(2)])
D_t

array([[ 0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [-0.5       , -0.5       ,  0.5       ,  0.5       ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [-0.70710678,  0.70710678,  0.        ,  0.        ]])

In [52]:
C@L@D_t

array([[1., 1., 2., 2.],
       [2., 2., 1., 1.]])

In [53]:
C@np.delete(L, np.s_[2:4:], 1)@np.delete(D_t, np.s_[2:4:], 0)

array([[1., 1., 2., 2.],
       [2., 2., 1., 1.]])

# 4в

In [54]:
A = np.array([[7 ,1 , 2],[5 ,5 , -2],[3 , 3 , 6],[-1 ,-7 ,-2]])
A

array([[ 7,  1,  2],
       [ 5,  5, -2],
       [ 3,  3,  6],
       [-1, -7, -2]])

In [55]:
S = A.T @A

In [56]:
S/12

array([[7., 4., 2.],
       [4., 7., 2.],
       [2., 2., 4.]])

In [57]:
12*12

144

In [58]:
L_144=S/12-12*np.identity(3)
L_144

array([[-5.,  4.,  2.],
       [ 4., -5.,  2.],
       [ 2.,  2., -8.]])

In [59]:
L_144[0]+=L_144[1]
L_144[0]*=-1
L_144

array([[ 1.,  1., -4.],
       [ 4., -5.,  2.],
       [ 2.,  2., -8.]])

In [60]:
L_144[1]+=-4*L_144[0]
L_144[2]+=-2*L_144[0]
L_144

array([[ 1.,  1., -4.],
       [ 0., -9., 18.],
       [ 0.,  0.,  0.]])

In [61]:
L_144[1]=L_144[1]/-9
L_144

array([[ 1.,  1., -4.],
       [-0.,  1., -2.],
       [ 0.,  0.,  0.]])

In [62]:
L_144[0]+=-1*L_144[1]
L_144

array([[ 1.,  0., -2.],
       [-0.,  1., -2.],
       [ 0.,  0.,  0.]])

In [63]:
np.array([2,2,1])@np.array([2,2,1])

9

In [64]:
L_36=S/12-3*np.identity(3)
L_36

array([[4., 4., 2.],
       [4., 4., 2.],
       [2., 2., 1.]])

In [65]:
np.array([-1,1,0])@np.array([-1,1,0])

2

In [66]:
np.array([-1/2,0,1])@np.array([-1/2,0,1])

1.25

In [67]:
v1 = np.array([2/3,2/3,1/3])
v2 = np.array([-1,1,0])
v3 = np.array([-1/2,0,1])
v3

array([-0.5,  0. ,  1. ])

In [68]:
v2@v3

0.5

In [69]:
v2@v2

2

In [70]:
u3 = v3-(1/4)*v2
u3

array([-0.25, -0.25,  1.  ])

In [71]:
u3@u3

1.125

In [72]:
u3 = u3/np.sqrt(u3@u3)
u3

array([-0.23570226, -0.23570226,  0.94280904])

In [73]:
v2 = v2/np.sqrt(v2@v2)
v2

array([-0.70710678,  0.70710678,  0.        ])

In [74]:
v1@v2

0.0

In [75]:
v1@u3

0.0

In [76]:
v2@u3

0.0

In [77]:
v1@v1

1.0

In [78]:
v2@v2

0.9999999999999998

In [79]:
u3@u3

1.0000000000000002

# 2a

In [80]:
C = np.array([[1/np.sqrt(2),1/np.sqrt(2)],[1/np.sqrt(2),-1/np.sqrt(2)]])
D = np.array([[3,0],[0,1]])
C@D@C.T

array([[2., 1.],
       [1., 2.]])

In [140]:
import numpy as np
C = np.array([[1/np.sqrt(2),1/np.sqrt(2)],[1/np.sqrt(2),-1/np.sqrt(2)]])
D = np.array([[1,0],[0,3]])
C@D@C.T

array([[ 2., -1.],
       [-1.,  2.]])

# 2b

In [141]:
C = np.array([[0,1/np.sqrt(2),-1/np.sqrt(2)],[1,0,0],[0,1/np.sqrt(2),1/np.sqrt(2)]])
D = np.array([[1,0,0],[0,1,0],[0,0,-1]])
C@D@C.T

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

# 3a

In [100]:
A = np.array([[13,14,4],[14,24,18],[4,18,29]])
A

array([[13, 14,  4],
       [14, 24, 18],
       [ 4, 18, 29]])

In [101]:
A_49=A-49*np.identity(3)
A_49

array([[-36.,  14.,   4.],
       [ 14., -25.,  18.],
       [  4.,  18., -20.]])

In [102]:
A_49[2]+=-1*A_49[0]
A_49

array([[-36.,  14.,   4.],
       [ 14., -25.,  18.],
       [ 40.,   4., -24.]])

In [103]:
A_49[2]*=1/4
A_49[0]*=-1/2
A_49

array([[ 18.,  -7.,  -2.],
       [ 14., -25.,  18.],
       [ 10.,   1.,  -6.]])

In [104]:
A_49[1]-=A_49[2]
A_49[1]*=1/2

A_49

array([[ 18.,  -7.,  -2.],
       [  2., -13.,  12.],
       [ 10.,   1.,  -6.]])

In [105]:
A_49[[1,0]]=A_49[[0,1]]
A_49

array([[  2., -13.,  12.],
       [ 18.,  -7.,  -2.],
       [ 10.,   1.,  -6.]])

In [106]:
A_49[1]-=A_49[0]*9
A_49[2]-=A_49[0]*5
A_49

array([[   2.,  -13.,   12.],
       [   0.,  110., -110.],
       [   0.,   66.,  -66.]])

In [107]:
A_49[1]*=1/110
A_49[2]-=A_49[1]*66

A_49

array([[  2., -13.,  12.],
       [  0.,   1.,  -1.],
       [  0.,   0.,   0.]])

In [108]:
A_49[0]+=A_49[1]*13

A_49

array([[ 2.,  0., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  0.]])

In [112]:
v1 = np.array([1,2,2])

In [113]:
np.linalg.norm(v1)

3.0

In [120]:
A_16=A-16*np.identity(3)
A_16

array([[-3., 14.,  4.],
       [14.,  8., 18.],
       [ 4., 18., 13.]])

In [121]:
A_16[2]+=A_16[0]
A_16[[0,2]]=A_16[[2,0]]
A_16

array([[ 1., 32., 17.],
       [14.,  8., 18.],
       [-3., 14.,  4.]])

In [122]:
A_16[1]-=A_16[0]*14
A_16[2]+=A_16[0]*3

A_16

array([[   1.,   32.,   17.],
       [   0., -440., -220.],
       [   0.,  110.,   55.]])

In [123]:
A_16[1]*=-1/220
A_16[2]-=A_16[1]*55

A_16

array([[ 1., 32., 17.],
       [-0.,  2.,  1.],
       [ 0.,  0.,  0.]])

In [124]:
A_16[0]-=A_16[1]*16

A_16

array([[ 1.,  0.,  1.],
       [-0.,  2.,  1.],
       [ 0.,  0.,  0.]])

In [132]:
B=A-np.identity(3)
B

array([[12., 14.,  4.],
       [14., 23., 18.],
       [ 4., 18., 28.]])

In [133]:
B[2]*=1/2
B[[0,2]]=B[[2,0]]
B

array([[ 2.,  9., 14.],
       [14., 23., 18.],
       [12., 14.,  4.]])

In [134]:
B[1]+=-7*B[0]
B[2]+=-6*B[0]

B

array([[  2.,   9.,  14.],
       [  0., -40., -80.],
       [  0., -40., -80.]])

In [135]:
B[1]*=-1/40
B[2]+=B[1]*40

B

array([[ 2.,  9., 14.],
       [-0.,  1.,  2.],
       [ 0.,  0.,  0.]])

In [136]:
B[0]+=B[1]*-9
B


array([[ 2.,  0., -4.],
       [-0.,  1.,  2.],
       [ 0.,  0.,  0.]])

In [146]:
C = np.array([[1,-2,2],[2,-1,-2],[2,2,1]])/3
C

array([[ 0.33333333, -0.66666667,  0.66666667],
       [ 0.66666667, -0.33333333, -0.66666667],
       [ 0.66666667,  0.66666667,  0.33333333]])

In [147]:
D=np.array([[49,0,0],[0,16,0],[0,0,1]])
D

array([[49,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  1]])

In [148]:
C@D@C.T

array([[13., 14.,  4.],
       [14., 24., 18.],
       [ 4., 18., 29.]])

In [154]:
D_sqrt = np.sqrt(D)

D_sqrt


array([[7., 0., 0.],
       [0., 4., 0.],
       [0., 0., 1.]])

In [155]:
D

array([[49,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  1]])

In [156]:
C@D_sqrt@C.T

array([[ 3.00000000e+00,  2.00000000e+00, -1.11022302e-16],
       [ 2.00000000e+00,  4.00000000e+00,  2.00000000e+00],
       [-1.11022302e-16,  2.00000000e+00,  5.00000000e+00]])

In [157]:
res_A = np.array([[3,2,0],[2,4,2],[0,2,5]])
res_A@res_A

array([[13, 14,  4],
       [14, 24, 18],
       [ 4, 18, 29]])