# 4a

In [1]:
import numpy as np

In [2]:
A = np.array([[5,1,8],[7,5,4]])
A

array([[5, 1, 8],
       [7, 5, 4]])

In [3]:
A.T

array([[5, 7],
       [1, 5],
       [8, 4]])

In [6]:
S = A@A.T
S

array([[90, 72],
       [72, 90]])

In [20]:
def tolatex_mat(M):
    for row in M:
        listr = row.tolist()
        converted_list = [str(element) for element in listr]
        joined_string = "&".join(converted_list)
        print(joined_string,"\\\\", sep="")
        
tolatex_mat(S)

90&72\\
72&90\\


In [21]:
np.linalg.det(S)

2916.000000000001

In [27]:
S.trace()

180

In [28]:
L_162=S-162*np.identity(2)
L_162

array([[-72.,  72.],
       [ 72., -72.]])

In [29]:
tolatex_mat(L_162)

-72.0&72.0\\
72.0&-72.0\\


In [30]:
L_18=S-18*np.identity(2)
L_18

array([[72., 72.],
       [72., 72.]])

In [31]:
tolatex_mat(L_18)

72.0&72.0\\
72.0&72.0\\


In [36]:
C=np.array([[1,0],[0,3]])
L=np.array([[1,1],[1,-1]])

In [37]:
Res = C@L@A

In [38]:
Res

array([[ 12,   6,  12],
       [ -6, -12,  12]])

In [39]:
tolatex_mat(Res)

12&6&12\\
-6&-12&12\\


In [41]:
Res = Res/18

In [44]:
Res[1]@Res[1]

1.0

In [45]:
Res

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.33333333, -0.66666667,  0.66666667]])

In [48]:
Res[0]@Res[1]

0.0

In [55]:
Solve_u2 = np.array([[2,1,2],[-1,-2,2]])
Solve_u2

array([[ 2,  1,  2],
       [-1, -2,  2]])

In [56]:
Solve_u2[0]=Solve_u2[0]+Solve_u2[1]
tolatex_mat(Solve_u2)

1&-1&4\\
-1&-2&2\\


In [57]:
Solve_u2[1]=Solve_u2[1]+Solve_u2[0]
tolatex_mat(Solve_u2)

1&-1&4\\
0&-3&6\\


In [58]:
Solve_u2[1]=Solve_u2[1]/-3
tolatex_mat(Solve_u2)

1&-1&4\\
0&1&-2\\


In [59]:
Solve_u2[0]=Solve_u2[0]+Solve_u2[1]
tolatex_mat(Solve_u2)

1&0&2\\
0&1&-2\\


In [61]:
u_3 = np.array([-2,2,1])
u_3@u_3

9

In [62]:
u_3 = u_3/3
u_3

array([-0.66666667,  0.66666667,  0.33333333])

In [67]:
D_t = np.vstack([np.array([[2,1,2],[-1,-2,2]])/3,u_3])
D_t

array([[ 0.66666667,  0.33333333,  0.66666667],
       [-0.33333333, -0.66666667,  0.66666667],
       [-0.66666667,  0.66666667,  0.33333333]])

In [68]:
C = L/np.sqrt(2)

In [69]:
C

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [71]:
L = np.array([[9*np.sqrt(2),0,0],[0,3*np.sqrt(2),0]])
L

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        ,  4.24264069,  0.        ]])

In [72]:
C@L@D_t

array([[5., 1., 8.],
       [7., 5., 4.]])

In [73]:
C@np.delete(L, 2, 1)@np.delete(D_t, 2, 0)

array([[5., 1., 8.],
       [7., 5., 4.]])

# 4b

In [76]:
A = np.array([[1, 1 ,  2 ,  2],[2 ,  2 ,  1,   1]])
A.T

array([[1, 2],
       [1, 2],
       [2, 1],
       [2, 1]])

In [77]:
S=A@A.T

In [78]:
S

array([[10,  8],
       [ 8, 10]])

In [80]:
S.trace()

20

In [81]:
np.linalg.det(S)

36.0

In [83]:
inv_l = np.array([[1,0],[0,3]])
c_t = np.array([[1,1],[1,-1]])
c_t

array([[ 1,  1],
       [ 1, -1]])

In [85]:
d1_t= inv_l@c_t@A/6
d1_t

array([[ 0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5]])

In [86]:
d1_t[0]@d1_t[0]

1.0

In [87]:
d1_t[0]@d1_t[1]

0.0

In [88]:
d1_t[1]@d1_t[1]

1.0

In [89]:
d2_find = 2*d1_t
d2_find

array([[ 1.,  1.,  1.,  1.],
       [-1., -1.,  1.,  1.]])

In [90]:
d2_find[1]+=d2_find[0]
d2_find

array([[1., 1., 1., 1.],
       [0., 0., 2., 2.]])

In [92]:
d2_find[1]=d2_find[1]/2
d2_find

array([[1., 1., 1., 1.],
       [0., 0., 1., 1.]])

In [93]:
d2_find[0]-=d2_find[1]
d2_find

array([[1., 1., 0., 0.],
       [0., 0., 1., 1.]])

In [94]:
d2_find[0]@d2_find[0]

2.0

In [95]:
C

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [96]:
L = np.array([[3*np.sqrt(2),0,0,0],[0,np.sqrt(2),0,0]])
L

array([[4.24264069, 0.        , 0.        , 0.        ],
       [0.        , 1.41421356, 0.        , 0.        ]])

In [97]:
d1_t

array([[ 0.5,  0.5,  0.5,  0.5],
       [-0.5, -0.5,  0.5,  0.5]])

In [100]:
D_t = np.vstack([d1_t,np.array([[0,0,-1,1],[-1,1,0,0]])/np.sqrt(2)])
D_t

array([[ 0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [-0.5       , -0.5       ,  0.5       ,  0.5       ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678],
       [-0.70710678,  0.70710678,  0.        ,  0.        ]])

In [101]:
C@L@D_t

array([[1., 1., 2., 2.],
       [2., 2., 1., 1.]])

In [106]:
C@np.delete(L, np.s_[2:4:], 1)@np.delete(D_t, np.s_[2:4:], 0)

array([[1., 1., 2., 2.],
       [2., 2., 1., 1.]])

# 4в

In [107]:
A = np.array([[7 ,1 , 2],[5 ,5 , -2],[3 , 3 , 6],[-1 ,-7 ,-2]])
A

array([[ 7,  1,  2],
       [ 5,  5, -2],
       [ 3,  3,  6],
       [-1, -7, -2]])

In [108]:
S = A.T @A

In [110]:
S/12

array([[7., 4., 2.],
       [4., 7., 2.],
       [2., 2., 4.]])

In [112]:
12*12

144

In [113]:
L_144=S/12-12*np.identity(3)
L_144

array([[-5.,  4.,  2.],
       [ 4., -5.,  2.],
       [ 2.,  2., -8.]])

In [114]:
L_144[0]+=L_144[1]
L_144[0]*=-1
L_144

array([[ 1.,  1., -4.],
       [ 4., -5.,  2.],
       [ 2.,  2., -8.]])

In [115]:
L_144[1]+=-4*L_144[0]
L_144[2]+=-2*L_144[0]
L_144

array([[ 1.,  1., -4.],
       [ 0., -9., 18.],
       [ 0.,  0.,  0.]])

In [116]:
L_144[1]=L_144[1]/-9
L_144

array([[ 1.,  1., -4.],
       [-0.,  1., -2.],
       [ 0.,  0.,  0.]])

In [117]:
L_144[0]+=-1*L_144[1]
L_144

array([[ 1.,  0., -2.],
       [-0.,  1., -2.],
       [ 0.,  0.,  0.]])

In [120]:
np.array([2,2,1])@np.array([2,2,1])

9

In [121]:
L_36=S/12-3*np.identity(3)
L_36

array([[4., 4., 2.],
       [4., 4., 2.],
       [2., 2., 1.]])

In [122]:
np.array([-1,1,0])@np.array([-1,1,0])

2

In [123]:
np.array([-1/2,0,1])@np.array([-1/2,0,1])

1.25

In [124]:
v1 = np.array([2/3,2/3,1/3])
v2 = np.array([-1,1,0])
v3 = np.array([-1/2,0,1])
v3

array([-0.5,  0. ,  1. ])

In [125]:
v2@v3

0.5

In [126]:
v2@v2

2

In [127]:
u3 = v3-(1/4)*v2
u3

array([-0.25, -0.25,  1.  ])

In [128]:
u3@u3

1.125

In [130]:
u3 = u3/np.sqrt(u3@u3)
u3

array([-0.23570226, -0.23570226,  0.94280904])

In [131]:
v2 = v2/np.sqrt(v2@v2)
v2

array([-0.70710678,  0.70710678,  0.        ])

In [132]:
v1@v2

0.0

In [133]:
v1@u3

0.0

In [134]:
v2@u3

0.0

In [135]:
v1@v1

1.0

In [136]:
v2@v2

0.9999999999999998

In [137]:
u3@u3

1.0000000000000002