In [2]:
import numpy as np

# 1

In [3]:
A = np.array([[1,2,3], [5,1,4], [3,2,5]])
A

array([[1, 2, 3],
       [5, 1, 4],
       [3, 2, 5]])

In [4]:
np.linalg.det(A)

-7.999999999999995

# 3

In [5]:
A = np.array([[4,4,-3], [2,3,-2], [4,5,-4]])

In [6]:
np.linalg.det(A)

-2.0

In [10]:
5*(-12+10)-2*(-8+5)+4*(-4+3)

-8

In [11]:
(5*(-16+15)-4*(-8+5)+4*(-6+4))

-1

In [12]:
(5*(-8+9)-4*(-4+3)+2*(-6+4))

5

# 6a

In [14]:
A = np.array([[1,1,0], [0,1,0], [0,3,3]]) 
np.linalg.inv(A)


array([[ 1.00000000e+00, -1.00000000e+00, -1.85037171e-17],
       [ 0.00000000e+00,  1.00000000e+00,  1.85037171e-17],
       [-0.00000000e+00, -1.00000000e+00,  3.33333333e-01]])

In [15]:
np.linalg.det(A)

3.0000000000000004

# 7

In [16]:
C = np.array([[1,2,3],[2,4,6],[3,6,9]])
B = np.array([[1,1,1],[1,2,3],[1,4,9]])

D = np.linalg.inv(B)
C @ D

array([[-4.44089210e-16,  1.00000000e+00, -1.11022302e-16],
       [-8.88178420e-16,  2.00000000e+00, -2.22044605e-16],
       [ 4.44089210e-16,  3.00000000e+00, -7.77156117e-16]])

In [17]:
D

array([[ 3. , -2.5,  0.5],
       [-3. ,  4. , -1. ],
       [ 1. , -1.5,  0.5]])